citation = [{'AB': 'Many policies and projects now encourage investigators to share their raw research data with other scientists. Unfortunately, it is difficult to measure the effectiveness of these initiatives because data can be shared in such a variety of mechanisms and locations. We propose a novel approach to finding shared datasets: using NLP techniques to identify declarations of dataset sharing within the full text of primary research articles. Using regular expression patterns and machine learning algorithms on open access biomedical literature, our system was able to identify 61% of articles with shared datasets with 80% precision. A simpler version of our classifier achieved higher recall (86%), though lower precision (49%). We believe our results demonstrate the feasibility of this approach and hope to inspire further study of dataset retrieval techniques and policy evaluation.',
  'AD': 'University of Pittsburgh, Pittsburgh, PA, USA.',
  'AU': ['Piwowar HA', 'Chapman WW'],
  'CRDT': ['2008/11/13 09:00'],
  'DA': '20081112',
  'DCOM': '20100108',
  'DEP': '20081106',
  'DP': '2008',
  'EDAT': '2008/11/13 09:00',
  'FAU': ['Piwowar, Heather A', 'Chapman, Wendy W'],
  'GR': ['1R01LM009427-01/LM/NLM NIH HHS/United States',
   '5T15-LM007059-19/LM/NLM NIH HHS/United States'],
  'IS': '1942-597X (Electronic) 1559-4076 (Linking)',
  'JID': '101209213',
  'JT': 'AMIA ... Annual Symposium proceedings / AMIA Symposium. AMIA Symposium',
  'LA': ['eng'],
  'LR': '20140902',
  'MH': ['Algorithms',
   'Artificial Intelligence',
   '*Cooperative Behavior',
   'Information Dissemination/*methods',
   'Information Storage and Retrieval/*methods',
   '*Natural Language Processing',
   'Pattern Recognition, Automated/*methods',
   'Periodicals as Topic/*classification',
   '*Subject Headings'],
  'MHDA': '2010/01/09 06:00',
  'OID': ['NLM: PMC2655927'],
  'OWN': 'NLM',
  'PG': '596-600',
  'PHST': ['2008/03/13 [received]', '2008/07/16 [revised]'],
  'PL': 'United States',
  'PMC': 'PMC2655927',
  'PMID': '18998887',
  'PST': 'epublish',
  'PT': ['Journal Article', 'Research Support, N.I.H., Extramural'],
  'SB': 'IM',
  'SO': 'AMIA Annu Symp Proc. 2008 Nov 6:596-600.',
  'STAT': 'MEDLINE',
  'TA': 'AMIA Annu Symp Proc',
  'TI': 'Identifying data sharing in biomedical literature.'}]