#!/usr/bin/python
# -*- coding: utf-8 -*-

temp_endpoint_data = [
  {
    "endpoint_id": "cc24ae45a1b04df2d21",
    "institution_name": "University of Chichester",
    "repo_name": "ChiPrints",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://eprints.chi.ac.uk/cgi/oai2",
    "most_recent_year_harvested": "2019-01-22 0:06:16",
    "request_id": "8b9e0e",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 400,
    "submittedVersion": 1214,
    "all_versions": 1614,
    "num_pmh_records": 1395,
    "num_pages_with_matches": 1594,
    "num_matching_pages_with_fulltext": 327
  },
  {
    "endpoint_id": "c14e7d56807a4dffda4",
    "institution_name": "UVic-UCC",
    "repo_name": "RIUVic",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://repositori.uvic.cat/oai/request",
    "most_recent_year_harvested": "2019-01-23 4:35:17",
    "request_id": "1079cb",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 75,
    "submittedVersion": 420,
    "all_versions": 495,
    "num_pmh_records": 241,
    "num_pages_with_matches": 228,
    "num_matching_pages_with_fulltext": 99
  },
  {
    "endpoint_id": "31ff7cae420a1121234",
    "institution_name": "University of Szeged",
    "repo_name": "SZTE Publicatio Repozitórium - SZTE - Repository of Publications",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://publicatio.bibl.u-szeged.hu/cgi/oai2",
    "most_recent_year_harvested": "2019-01-23 3:12:53",
    "request_id": "b99891",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 9008,
    "submittedVersion": 12278,
    "all_versions": 21286,
    "num_pmh_records": 9116,
    "num_pages_with_matches": 9371,
    "num_matching_pages_with_fulltext": 4488
  },
  {
    "endpoint_id": "83ff48d6dc162d7c721",
    "institution_name": "Cardiff University",
    "repo_name": "ORCA Online Research @Cardiff",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://orca.cf.ac.uk/cgi/oai2",
    "most_recent_year_harvested": "2019-01-22 23:56:54",
    "request_id": "94c82d",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 57243,
    "submittedVersion": 86842,
    "all_versions": 144085,
    "num_pmh_records": 25929,
    "num_pages_with_matches": 46257,
    "num_matching_pages_with_fulltext": 30886
  },
  {
    "endpoint_id": "ee9a2f2e726c182cb8a",
    "institution_name": "Indiana University",
    "repo_name": "IUScholarWorks",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://scholarworks.iu.edu/dspace-oai/request",
    "most_recent_year_harvested": "2019-01-23 3:44:28",
    "request_id": "39da35",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 2025,
    "submittedVersion": 4629,
    "all_versions": 6654,
    "num_pmh_records": 9196,
    "num_pages_with_matches": 9020,
    "num_matching_pages_with_fulltext": 1351
  },
  {
    "endpoint_id": "473c32722da5ae169cc",
    "institution_name": "University of Oklahoma",
    "repo_name": "Interdisciplinary Journal of Signage and Wayfinding",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://ijsw.shareok.org/ijsw/oai",
    "most_recent_year_harvested": "2019-01-21 16:55:57",
    "request_id": "bf64ce",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": 75,
    "all_versions": 75,
    "num_pmh_records": 20,
    "num_pages_with_matches": 28,
    "num_matching_pages_with_fulltext": 28
  },
  {
    "endpoint_id": "78c18d0555cb3a3478e",
    "institution_name": "ISEL: Instituto Superior de Engenharia de Lisboa",
    "repo_name": "i-ETC: ISEL Academic Journal of Electronics, Telecommunications and Computers",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://journals.isel.pt/index.php/i-ETC/oai",
    "most_recent_year_harvested": "2019-01-22 17:07:41",
    "request_id": "6942a0",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 40,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "5453dadb3a1f1aaf099",
    "institution_name": "University of Texas Rio Grande Valley",
    "repo_name": "University of Texas Rio Grande Valley DSpace Repository",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://utrgv-ir.tdl.org/oai/request",
    "most_recent_year_harvested": "2019-01-22 23:50:35",
    "request_id": "278f34",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": 20,
    "all_versions": 20,
    "num_pmh_records": 761,
    "num_pages_with_matches": 4,
    "num_matching_pages_with_fulltext": 4
  },
  {
    "endpoint_id": "97aa526343b06bea6c9",
    "institution_name": "Swiss Federal Institute for Forest, Snow and Landscape Research",
    "repo_name": "DORA WSL",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://www.dora.lib4ri.ch/wsl/oai2",
    "most_recent_year_harvested": "2019-01-23 12:41:06",
    "request_id": "ea6813",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": 65,
    "all_versions": 65,
    "num_pmh_records": 690,
    "num_pages_with_matches": 34,
    "num_matching_pages_with_fulltext": 13
  },
  {
    "endpoint_id": "0e7511e16a13645b5be",
    "institution_name": "Aston University",
    "repo_name": "Aston Publications Explorer",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://publications.aston.ac.uk/cgi/oai2",
    "most_recent_year_harvested": "2019-01-22 21:01:29",
    "request_id": 343033,
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 15755,
    "submittedVersion": 26733,
    "all_versions": 42488,
    "num_pmh_records": 7803,
    "num_pages_with_matches": 7675,
    "num_matching_pages_with_fulltext": 7364
  },
  {
    "endpoint_id": "adf369f02773439b73d",
    "institution_name": "Universidad Pública de Navarra",
    "repo_name": "Academica-e",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://academica-e.unavarra.es/oai/driver",
    "most_recent_year_harvested": "2019-01-22 23:46:07",
    "request_id": "e8abaa",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "16b0ec347efa9f3a6c8",
    "institution_name": "Lunar and Planetary Institute",
    "repo_name": "USRA Houston Repository",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://repository.hou.usra.edu/oai/request",
    "most_recent_year_harvested": "2019-01-22 15:47:30",
    "request_id": "b83075",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 5,
    "submittedVersion": 20,
    "all_versions": 25,
    "num_pmh_records": 1196,
    "num_pages_with_matches": 10,
    "num_matching_pages_with_fulltext": 5
  },
  {
    "endpoint_id": "ed6ed0d7130b2560419",
    "institution_name": "University of Louisville",
    "repo_name": "ThinkIR: The University of Louisville's Institutional Repository",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://ir.library.louisville.edu/do/oai/",
    "most_recent_year_harvested": "2019-01-22 23:42:40",
    "request_id": "bdfe88",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 4920,
    "submittedVersion": 9866,
    "all_versions": 14786,
    "num_pmh_records": 3690,
    "num_pages_with_matches": 5936,
    "num_matching_pages_with_fulltext": 5889
  },
  {
    "endpoint_id": "b852bebdf5d820ad965",
    "institution_name": "University of Southern Mississippi",
    "repo_name": "Aquila Digital Community",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://aquila.usm.edu/do/oai/",
    "most_recent_year_harvested": "2019-01-22 16:14:30",
    "request_id": "76decd",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 25,
    "submittedVersion": 30,
    "all_versions": 55,
    "num_pmh_records": 771,
    "num_pages_with_matches": 112,
    "num_matching_pages_with_fulltext": 20
  },
  {
    "endpoint_id": "2a079251f95f37491a1",
    "institution_name": "University of Oklahoma",
    "repo_name": "Study and Scrutiny: Research on Young Adult Literature",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://journals.shareok.org/studyandscrutiny/oai",
    "most_recent_year_harvested": "2019-01-22 23:50:28",
    "request_id": "4e1c9c",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": 120,
    "all_versions": 120,
    "num_pmh_records": 34,
    "num_pages_with_matches": 43,
    "num_matching_pages_with_fulltext": 43
  },
  {
    "endpoint_id": "610427bfcf3b52f5589",
    "institution_name": "Concordia University",
    "repo_name": "Spectrum Research Repository",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://spectrum.library.concordia.ca/cgi/oai2",
    "most_recent_year_harvested": "2019-01-23 2:58:57",
    "request_id": "9a0244",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 2305,
    "submittedVersion": 8830,
    "all_versions": 11135,
    "num_pmh_records": 15915,
    "num_pages_with_matches": 2527,
    "num_matching_pages_with_fulltext": 2239
  },
  {
    "endpoint_id": "90389dd407c73f9e281",
    "institution_name": "Université de Lausanne",
    "repo_name": "SERVAL",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://serval.unil.ch/oaiprovider",
    "most_recent_year_harvested": "2019-01-21 13:45:58",
    "request_id": "ee8462",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 16819,
    "submittedVersion": 20516,
    "all_versions": 37335,
    "num_pmh_records": 63816,
    "num_pages_with_matches": 91688,
    "num_matching_pages_with_fulltext": 21678
  },
  {
    "endpoint_id": "31a627d215f9128df44",
    "institution_name": "University of Windsor",
    "repo_name": "Scholarship at UWindsor",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://scholar.uwindsor.ca/do/oai/",
    "most_recent_year_harvested": "2019-01-23 3:48:10",
    "request_id": "15d39f",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 1591,
    "submittedVersion": 3095,
    "all_versions": 4686,
    "num_pmh_records": 14422,
    "num_pages_with_matches": 4153,
    "num_matching_pages_with_fulltext": 1662
  },
  {
    "endpoint_id": "1bf0a5bda3ea43c6dec",
    "institution_name": "Digital Commons - Bepress",
    "repo_name": "Scholarly Communication and Research at Bates (SCARAB)",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://scarab.bates.edu/do/oai/",
    "most_recent_year_harvested": "2019-01-22 23:58:11",
    "request_id": "ddb3e8",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 24,
    "submittedVersion": 53,
    "all_versions": 77,
    "num_pmh_records": 3663,
    "num_pages_with_matches": 57,
    "num_matching_pages_with_fulltext": 26
  },
  {
    "endpoint_id": "da9e172954cdaaadd6f",
    "institution_name": "University of Belgrade, Institute for Philosophy and Social Theory",
    "repo_name": "Repository of the Institute for Philosophy and Social Theory",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://rifdt.instifdt.bg.ac.rs/oai/request",
    "most_recent_year_harvested": "2019-01-22 23:42:13",
    "request_id": "f52008",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 50,
    "submittedVersion": 1946,
    "all_versions": 1996,
    "num_pmh_records": 1895,
    "num_pages_with_matches": 552,
    "num_matching_pages_with_fulltext": 477
  },
  {
    "endpoint_id": "c7d6498c733ce6dbcc1",
    "institution_name": "Rhodes University",
    "repo_name": "Rhodes University - Hosted Journals",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://journal.ru.ac.za/index.php/index/oai",
    "most_recent_year_harvested": "2019-01-23 3:10:00",
    "request_id": "d68a00",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 5,
    "submittedVersion": 3305,
    "all_versions": 3310,
    "num_pmh_records": 1158,
    "num_pages_with_matches": 1014,
    "num_matching_pages_with_fulltext": 662
  },
  {
    "endpoint_id": "fe0bcb24c679e90e44a",
    "institution_name": "Research Institute for Nature and Forest",
    "repo_name": "INBO PURE Portal",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://purews.inbo.be/ws/oai",
    "most_recent_year_harvested": "2019-01-22 23:41:14",
    "request_id": "55fb81",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 636,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "9572eaee815e41c48ae",
    "institution_name": "Universidad de Zaragoza",
    "repo_name": "Zaguan",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://zaguan.unizar.es/oai2d",
    "most_recent_year_harvested": "",
    "request_id": "dcc3e8",
    "error": "error in safe_get_next_record; try again",
    "acceptedVersion": "",
    "publishedVersion": 1685,
    "submittedVersion": 2525,
    "all_versions": 4210,
    "num_pmh_records": 15442,
    "num_pages_with_matches": 844,
    "num_matching_pages_with_fulltext": 842
  },
  {
    "endpoint_id": "3f1cbedc158bf483445",
    "institution_name": "Università Cattolica del Sacro Cuore",
    "repo_name": "PubliCatt",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://publicatt.unicatt.it/oai/driver",
    "most_recent_year_harvested": "2019-01-22 23:54:14",
    "request_id": 94470,
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 910,
    "submittedVersion": 980,
    "all_versions": 1890,
    "num_pmh_records": 782,
    "num_pages_with_matches": 492,
    "num_matching_pages_with_fulltext": 423
  },
  {
    "endpoint_id": "fa9621202fc0bd3a29d",
    "institution_name": "University of Regina",
    "repo_name": "oURspace",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://ourspace.uregina.ca/oai/request",
    "most_recent_year_harvested": "2019-01-22 23:50:37",
    "request_id": "31ae09",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 135,
    "submittedVersion": 230,
    "all_versions": 365,
    "num_pmh_records": 7407,
    "num_pages_with_matches": 99,
    "num_matching_pages_with_fulltext": 94
  },
  {
    "endpoint_id": "f53d6355f0949c64e28",
    "institution_name": "Kooperativer Bibliotheksverbund Berlin-Brandenburg (KOBV), on behalf of the Universitätsbibliothek Erlangen-Nürnberg",
    "repo_name": "OPUS FAU - Online-Publikationssystem der Friedrich-Alexander-Universität Erlangen-Nürnberg",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://opus4.kobv.de/opus4-fau/oai",
    "most_recent_year_harvested": "2019-01-22 23:49:09",
    "request_id": "1bb71e",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 7483,
    "submittedVersion": 7885,
    "all_versions": 15368,
    "num_pmh_records": 7598,
    "num_pages_with_matches": 19122,
    "num_matching_pages_with_fulltext": 16152
  },
  {
    "endpoint_id": "d9e9d558f9e9de8afbc",
    "institution_name": "Univeristy of Trieste https://www.units.it/",
    "repo_name": "OpenstarTs",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://www.openstarts.units.it/dspace-oai/request",
    "most_recent_year_harvested": "2019-01-23 7:46:26",
    "request_id": "250e8d",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": 715,
    "all_versions": 715,
    "num_pmh_records": 18210,
    "num_pages_with_matches": 14761,
    "num_matching_pages_with_fulltext": 143
  },
  {
    "endpoint_id": "5bd65a68455459ea296",
    "institution_name": "Oslo Metropolitan University",
    "repo_name": "Open Digital Archive (ODA)",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://oda-hioa.archive.knowledgearc.net/oai/request",
    "most_recent_year_harvested": "2019-01-22 23:54:12",
    "request_id": "843fd2",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 4634,
    "submittedVersion": 8665,
    "all_versions": 13299,
    "num_pmh_records": 4592,
    "num_pages_with_matches": 2972,
    "num_matching_pages_with_fulltext": 2722
  },
  {
    "endpoint_id": "8009cf0c54db8591aba",
    "institution_name": "The OAPEN Foundation",
    "repo_name": "OAPEN",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://dataprovider.oapen.org/cgi/oapen",
    "most_recent_year_harvested": "2019-01-22 23:46:07",
    "request_id": "8ba1cb",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 5,
    "submittedVersion": 155,
    "all_versions": 160,
    "num_pmh_records": 33,
    "num_pages_with_matches": 16,
    "num_matching_pages_with_fulltext": 14
  },
  {
    "endpoint_id": "cc556934205f2dea5a6",
    "institution_name": "Northumbria University",
    "repo_name": "Northumbria Research Link",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://nrl.northumbria.ac.uk/cgi/oai2",
    "most_recent_year_harvested": "2019-01-22 16:00:19",
    "request_id": 1930000000000,
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 14390,
    "submittedVersion": 31249,
    "all_versions": 45639,
    "num_pmh_records": 9830,
    "num_pages_with_matches": 16404,
    "num_matching_pages_with_fulltext": 9439
  },
  {
    "endpoint_id": "56760cd8050689f40f1",
    "institution_name": "Facultad de Humanidades y Ciencias de la Educación, Universidad Nacional de La Plata",
    "repo_name": "Memoria Académica",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://www.memoria.fahce.unlp.edu.ar/oaiserver.cgi",
    "most_recent_year_harvested": "2019-01-22 23:42:19",
    "request_id": "ce3a5e",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 19,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "b1c0aa3f5573199df2d",
    "institution_name": "University of the Sunshine Coast",
    "repo_name": "USC Research Bank",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://research.usc.edu.au/vital/oai/provider",
    "most_recent_year_harvested": "2019-01-23 0:10:15",
    "request_id": "a1fbce",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 9125,
    "submittedVersion": 8270,
    "all_versions": 17395,
    "num_pmh_records": 22570,
    "num_pages_with_matches": 20892,
    "num_matching_pages_with_fulltext": 3550
  },
  {
    "endpoint_id": "8c3515cffcfc675f42c",
    "institution_name": "University of Oklahoma",
    "repo_name": "Journal of Higher Education Athletics & Innovation",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://journals.shareok.org/jheai/oai",
    "most_recent_year_harvested": "2019-01-22 15:52:20",
    "request_id": "2323f9",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 5,
    "submittedVersion": 95,
    "all_versions": 100,
    "num_pmh_records": 27,
    "num_pages_with_matches": 62,
    "num_matching_pages_with_fulltext": 52
  },
  {
    "endpoint_id": "0270f00978570ea91b4",
    "institution_name": "Applied and Natural Science Foundation",
    "repo_name": "Journal of Applied and Natural Science",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://journals.ansfoundation.org/index.php/jans/oai",
    "most_recent_year_harvested": "2019-01-22 23:59:11",
    "request_id": "b7b69f",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 7895,
    "submittedVersion": 105,
    "all_versions": 8000,
    "num_pmh_records": 1831,
    "num_pages_with_matches": 4001,
    "num_matching_pages_with_fulltext": 3636
  },
  {
    "endpoint_id": "d5c3782bf57be830829",
    "institution_name": "DOAJ. WORLDCAT, PKP Index, DataCie",
    "repo_name": "Journal of Advanced Laboratory Research in Biology",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://e-journal.sospublication.co.in/index.php/jalrb/oai",
    "most_recent_year_harvested": "2019-01-22 16:03:31",
    "request_id": "047923",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 242,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "9ee8fd05fec9ff060f5",
    "institution_name": "Thomas Jefferson University",
    "repo_name": "Jefferson Digital Commons",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://jdc.jefferson.edu/do/oai/",
    "most_recent_year_harvested": "2019-01-23 7:39:12",
    "request_id": 640700,
    "error": "",
    "acceptedVersion": 290,
    "publishedVersion": 5434,
    "submittedVersion": 11331,
    "all_versions": 17055,
    "num_pmh_records": 14660,
    "num_pages_with_matches": 6613,
    "num_matching_pages_with_fulltext": 6173
  },
  {
    "endpoint_id": "d5f346d79be5d342b0c",
    "institution_name": "University of Redlands",
    "repo_name": "InSPIRe@Redlands",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://inspire.redlands.edu/do/oai/",
    "most_recent_year_harvested": "2019-01-22 23:41:15",
    "request_id": "baddac",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": 90,
    "all_versions": 90,
    "num_pmh_records": 1291,
    "num_pages_with_matches": 143,
    "num_matching_pages_with_fulltext": 34
  },
  {
    "endpoint_id": "916a43b25af04e66dcd",
    "institution_name": "University of Zurich",
    "repo_name": "HOPE (Hauptbibliothek Open Publishing Environment)",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://www.hope.uzh.ch/oai",
    "most_recent_year_harvested": "2019-01-22 23:41:13",
    "request_id": "5cc0cc",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 5,
    "submittedVersion": 5,
    "all_versions": 10,
    "num_pmh_records": 795,
    "num_pages_with_matches": 70,
    "num_matching_pages_with_fulltext": 2
  },
  {
    "endpoint_id": "26e004febad4b787988",
    "institution_name": "GSI Helmholtzzentrum für Schwerionenforschung",
    "repo_name": "GSI Repository",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://repository.gsi.de/oai2d",
    "most_recent_year_harvested": "2019-01-23 8:02:25",
    "request_id": "7900a7",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 72,
    "submittedVersion": 152,
    "all_versions": 224,
    "num_pmh_records": 1197,
    "num_pages_with_matches": 1599,
    "num_matching_pages_with_fulltext": 108
  },
  {
    "endpoint_id": "fa2cfc885574aa6a406",
    "institution_name": "St. John Fisher College",
    "repo_name": "Fisher Digital Publications",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://fisherpub.sjfc.edu/do/oai/",
    "most_recent_year_harvested": "2019-01-22 23:50:30",
    "request_id": "d1b314",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 325,
    "submittedVersion": 340,
    "all_versions": 665,
    "num_pmh_records": 5179,
    "num_pages_with_matches": 570,
    "num_matching_pages_with_fulltext": 264
  },
  {
    "endpoint_id": "f9e2bd810f85da6b6c2",
    "institution_name": "Oslo Metropolitan University",
    "repo_name": "Fagarkivet",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://fagarkivet-hioa.archive.knowledgearc.net/oai/request",
    "most_recent_year_harvested": "2019-01-22 23:47:31",
    "request_id": "8ab375",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": 20,
    "all_versions": 20,
    "num_pmh_records": 1023,
    "num_pages_with_matches": 5,
    "num_matching_pages_with_fulltext": 4
  },
  {
    "endpoint_id": "38b6899f00d0ca86f03",
    "institution_name": "Indian Institute of Science",
    "repo_name": "ePrints@IISc",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://eprints.iisc.ac.in/cgi/oai2",
    "most_recent_year_harvested": "2019-01-14 20:45:17",
    "request_id": "84b053",
    "error": "RequestException in set_identify_info",
    "acceptedVersion": "",
    "publishedVersion": 4505,
    "submittedVersion": 16051,
    "all_versions": 20556,
    "num_pmh_records": 39041,
    "num_pages_with_matches": 42823,
    "num_matching_pages_with_fulltext": 4123
  },
  {
    "endpoint_id": "5416cbf1d4262ebcccf",
    "institution_name": "Texas Digital Library",
    "repo_name": "Texas ScholarWorks",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://repositories.lib.utexas.edu/utexas-oai/request",
    "most_recent_year_harvested": "2019-01-23 10:38:07",
    "request_id": "c52f0b",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 9695,
    "submittedVersion": 11945,
    "all_versions": 21640,
    "num_pmh_records": 59715,
    "num_pages_with_matches": 8836,
    "num_matching_pages_with_fulltext": 4328
  },
  {
    "endpoint_id": "5b0e17035c949ebd6ac",
    "institution_name": "Deakin University",
    "repo_name": "Deakin Research Online",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://dro.deakin.edu.au/oai.php",
    "most_recent_year_harvested": "2008-01-01 0:00:00",
    "request_id": "041afa",
    "error": "error in safe_get_next_record; try again",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "9332e53ae6244836d8b",
    "institution_name": "Swiss Federal Laboratories for Materials Science and Technology (Empa)",
    "repo_name": "DORA Empa",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://www.dora.lib4ri.ch/empa/oai2",
    "most_recent_year_harvested": "2019-01-22 15:41:27",
    "request_id": "029a8d",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 5,
    "submittedVersion": 35,
    "all_versions": 40,
    "num_pmh_records": 342,
    "num_pages_with_matches": 36,
    "num_matching_pages_with_fulltext": 8
  },
  {
    "endpoint_id": "5fd402771ef1f1c7a94",
    "institution_name": "University of San Diego",
    "repo_name": "Digital USD",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://digital.sandiego.edu/do/oai/",
    "most_recent_year_harvested": "2019-01-23 3:15:03",
    "request_id": "eb3109",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 245,
    "submittedVersion": 209,
    "all_versions": 454,
    "num_pmh_records": 14943,
    "num_pages_with_matches": 314,
    "num_matching_pages_with_fulltext": 170
  },
  {
    "endpoint_id": "daa6cb0af9452fe9c38",
    "institution_name": "Dublin Business School",
    "repo_name": "eSource",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://esource.dbs.ie/oai/request",
    "most_recent_year_harvested": "2019-01-22 23:50:15",
    "request_id": "864ded",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": 420,
    "all_versions": 420,
    "num_pmh_records": 2823,
    "num_pages_with_matches": 89,
    "num_matching_pages_with_fulltext": 84
  },
  {
    "endpoint_id": "8780ca025a02a67e451",
    "institution_name": "Corvinus University of Budapest",
    "repo_name": "Corvinus Research Archive",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://unipub.lib.uni-corvinus.hu/cgi/oai2",
    "most_recent_year_harvested": "2019-01-22 0:10:37",
    "request_id": "c27f1b",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 415,
    "submittedVersion": 5490,
    "all_versions": 5905,
    "num_pmh_records": 3207,
    "num_pages_with_matches": 3839,
    "num_matching_pages_with_fulltext": 1379
  },
  {
    "endpoint_id": "e2660c3188caae41be7",
    "institution_name": "MacOdrum Library, Carleton University",
    "repo_name": "Carleton University's Institutional Repository",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://ir.library.carleton.ca/oai/openaccess",
    "most_recent_year_harvested": "2019-01-22 17:22:45",
    "request_id": "2a8821",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 4015,
    "submittedVersion": 5760,
    "all_versions": 9775,
    "num_pmh_records": 2397,
    "num_pages_with_matches": 5675,
    "num_matching_pages_with_fulltext": 3696
  },
  {
    "endpoint_id": "bd26192e3f21d590a4f",
    "institution_name": "University Library Bern",
    "repo_name": "BORIS - Bern Open Repository and Information System",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://boris.unibe.ch/cgi/oai2",
    "most_recent_year_harvested": "2019-01-22 2:02:04",
    "request_id": "01c7c9",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 42297,
    "submittedVersion": 43016,
    "all_versions": 85313,
    "num_pmh_records": 31636,
    "num_pages_with_matches": 66769,
    "num_matching_pages_with_fulltext": 17346
  },
  {
    "endpoint_id": "ba159052b9ed76f8bf1",
    "institution_name": "University of Bologna",
    "repo_name": "AMS Acta",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://amsacta.unibo.it/cgi/oai2",
    "most_recent_year_harvested": "2019-01-22 10:09:03",
    "request_id": "0f6d46",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 25,
    "submittedVersion": 40,
    "all_versions": 65,
    "num_pmh_records": 35,
    "num_pages_with_matches": 26,
    "num_matching_pages_with_fulltext": 13
  },
  {
    "endpoint_id": "c4733583241652616be",
    "institution_name": "University of Oklahoma",
    "repo_name": "American Review of Politics",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://journals.shareok.org/arp/oai",
    "most_recent_year_harvested": "2019-01-22 23:42:16",
    "request_id": "b800b7",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 405,
    "submittedVersion": 1330,
    "all_versions": 1735,
    "num_pmh_records": 550,
    "num_pages_with_matches": 399,
    "num_matching_pages_with_fulltext": 377
  },
  {
    "endpoint_id": "8ca63fc98c69f8476a8",
    "institution_name": "Peertechz Publications",
    "repo_name": "Rajesh Varma",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://www.peertechz.com/oai-pmh",
    "most_recent_year_harvested": "2019-01-22 15:52:32",
    "request_id": "fd590d",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 1780,
    "submittedVersion": 3900,
    "all_versions": 5680,
    "num_pmh_records": 1922,
    "num_pages_with_matches": 3463,
    "num_matching_pages_with_fulltext": 1136
  },
  {
    "endpoint_id": "19af5a185bb9d620606",
    "institution_name": "Chalmers University of Technology",
    "repo_name": "Chalmers Research",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://research.chalmers.se/oai-pmh/general/",
    "most_recent_year_harvested": "2019-01-22 8:25:14",
    "request_id": "02bb31",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 27575,
    "submittedVersion": 31850,
    "all_versions": 59425,
    "num_pmh_records": 69127,
    "num_pages_with_matches": 56337,
    "num_matching_pages_with_fulltext": 12350
  },
  {
    "endpoint_id": "85d45bd14fb7bca0250",
    "institution_name": "American Chemical Society",
    "repo_name": "ChemRxiv",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://api.figshare.com/v2/oai",
    "most_recent_year_harvested": "2019-01-21 18:27:49",
    "request_id": "1d2f0c",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 30,
    "submittedVersion": 2045,
    "all_versions": 2075,
    "num_pmh_records": 1077,
    "num_pages_with_matches": 986,
    "num_matching_pages_with_fulltext": 419
  },
  {
    "endpoint_id": "d30f589ffed59d67cf2",
    "institution_name": "University of Oulu",
    "repo_name": "University of Oulu Repository - Jultika",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://jultika.oulu.fi/OAI/Server",
    "most_recent_year_harvested": "2019-01-23 14:47:09",
    "request_id": "9923f8",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 2250,
    "submittedVersion": 4985,
    "all_versions": 7235,
    "num_pmh_records": 9190,
    "num_pages_with_matches": 4292,
    "num_matching_pages_with_fulltext": 1449
  },
  {
    "endpoint_id": "fe1cde9531f1cef12ab",
    "institution_name": "Université de Limoges",
    "repo_name": "Trayectorias Humanas Trascontinentales",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://www.unilim.fr/trahs/oai.php",
    "most_recent_year_harvested": "2017-01-01 0:00:00",
    "request_id": "a8a109",
    "error": "error in safe_get_next_record; try again",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "ecb9d0ad28d7d71f632",
    "institution_name": "University of Massachusetts Amherst",
    "repo_name": "ScholarWorks@UMassAmherst",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://scholarworks.umass.edu/do/oai/",
    "most_recent_year_harvested": "2019-01-23 14:33:52",
    "request_id": "22dba0",
    "error": "",
    "acceptedVersion": 50,
    "publishedVersion": 7014,
    "submittedVersion": 23196,
    "all_versions": 30260,
    "num_pmh_records": 62619,
    "num_pages_with_matches": 31267,
    "num_matching_pages_with_fulltext": 13001
  },
  {
    "endpoint_id": "0ba602c3105ef29dd0c",
    "institution_name": "University of the Pacific",
    "repo_name": "Scholarly Commons",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://scholarlycommons.pacific.edu/do/oai/",
    "most_recent_year_harvested": "2019-01-21 16:49:30",
    "request_id": "d96161",
    "error": "",
    "acceptedVersion": 5,
    "publishedVersion": 413,
    "submittedVersion": 1020,
    "all_versions": 1438,
    "num_pmh_records": 38601,
    "num_pages_with_matches": 2074,
    "num_matching_pages_with_fulltext": 480
  },
  {
    "endpoint_id": "ea7bf8a2e14c1bce63f",
    "institution_name": "Institute of Animal Husbandry",
    "repo_name": "RIStocar - Repository of the Institute of Animal Husbandry",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://r.istocar.bg.ac.rs/oai/request",
    "most_recent_year_harvested": "2019-01-22 17:23:30",
    "request_id": "00628a",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 5,
    "submittedVersion": 1910,
    "all_versions": 1915,
    "num_pmh_records": 585,
    "num_pages_with_matches": 413,
    "num_matching_pages_with_fulltext": 385
  },
  {
    "endpoint_id": "646961d71158ecdef89",
    "institution_name": "Universitat Jaume I",
    "repo_name": "Repositori UJI",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://repositori.uji.es/oai/request",
    "most_recent_year_harvested": "2019-01-13 9:19:20",
    "request_id": "eb0219",
    "error": "RequestException in set_identify_info",
    "acceptedVersion": "",
    "publishedVersion": 2915,
    "submittedVersion": 18534,
    "all_versions": 21449,
    "num_pmh_records": 24105,
    "num_pages_with_matches": 20747,
    "num_matching_pages_with_fulltext": 4108
  },
  {
    "endpoint_id": "11fb549862f562d077e",
    "institution_name": "Max Planck Society",
    "repo_name": "MPG.PuRe",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://pure.mpg.de/oai/provider",
    "most_recent_year_harvested": "2019-01-23 8:09:21",
    "request_id": "fedd1c",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 56860,
    "submittedVersion": 108232,
    "all_versions": 165092,
    "num_pmh_records": 356487,
    "num_pages_with_matches": 248586,
    "num_matching_pages_with_fulltext": 63466
  },
  {
    "endpoint_id": "63ff73dc7fb5e17537d",
    "institution_name": "University of Padova",
    "repo_name": "Padua Research Archive",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://www.research.unipd.it/oai/request",
    "most_recent_year_harvested": "2019-01-22 23:38:12",
    "request_id": 1568,
    "error": "",
    "acceptedVersion": 5,
    "publishedVersion": 8369,
    "submittedVersion": 13709,
    "all_versions": 22083,
    "num_pmh_records": 203473,
    "num_pages_with_matches": 83820,
    "num_matching_pages_with_fulltext": 4757
  },
  {
    "endpoint_id": "3a398cd07ed1a5eb011",
    "institution_name": "Helmholtz-Zentrum Berlin für Materialien und Energie GmbH (HZB)",
    "repo_name": "HZB Repository",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://www.helmholtz-berlin.de/pubbin/oai",
    "most_recent_year_harvested": "2019-01-22 17:07:45",
    "request_id": "2da322",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 180,
    "submittedVersion": 1690,
    "all_versions": 1870,
    "num_pmh_records": 14845,
    "num_pages_with_matches": 10329,
    "num_matching_pages_with_fulltext": 375
  },
  {
    "endpoint_id": "a6f03fcea35f4af6266",
    "institution_name": "Aix Marseille Université",
    "repo_name": "HAL AMU",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://api.archives-ouvertes.fr/oai/ujm",
    "most_recent_year_harvested": "2019-01-23 8:11:39",
    "request_id": "7f6c3f",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 1365,
    "submittedVersion": 9923,
    "all_versions": 11288,
    "num_pmh_records": 25665,
    "num_pages_with_matches": 14177,
    "num_matching_pages_with_fulltext": 6936
  },
  {
    "endpoint_id": "05d3692e77c9947bc4f",
    "institution_name": "Univesrity of Belgrade, Faculty of Chemistry",
    "repo_name": "Cherry - Repository of the Faculty of Chemistry, University of Belgrade",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://cherry.chem.bg.ac.rs/oai/request",
    "most_recent_year_harvested": "2019-01-22 17:23:13",
    "request_id": "9b2635",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 375,
    "submittedVersion": 1675,
    "all_versions": 2050,
    "num_pmh_records": 2801,
    "num_pages_with_matches": 1786,
    "num_matching_pages_with_fulltext": 428
  },
  {
    "endpoint_id": "5aee1b3c3af727575e8",
    "institution_name": "University of Cambridge",
    "repo_name": "Apollo",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://www.repository.cam.ac.uk/oai/request",
    "most_recent_year_harvested": "2019-01-23 3:35:05",
    "request_id": "b50761",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 29295,
    "submittedVersion": 45270,
    "all_versions": 74565,
    "num_pmh_records": 219586,
    "num_pages_with_matches": 23216,
    "num_matching_pages_with_fulltext": 16765
  },
  {
    "endpoint_id": "8b8973339915aaf5729",
    "institution_name": "College of William & Mary",
    "repo_name": "W&M Publish",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://publish.wm.edu/do/oai/",
    "most_recent_year_harvested": "2019-01-22 23:42:18",
    "request_id": "ccd0a1",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 2250,
    "submittedVersion": 3860,
    "all_versions": 6110,
    "num_pmh_records": 11723,
    "num_pages_with_matches": 2697,
    "num_matching_pages_with_fulltext": 2235
  },
  {
    "endpoint_id": "7b1859f5e72ed7c467f",
    "institution_name": "Elsevier",
    "repo_name": "VU Research Portal",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://research.vu.nl/ws/oai",
    "most_recent_year_harvested": "2019-01-22 8:58:53",
    "request_id": "d365f7",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 34547,
    "submittedVersion": 55570,
    "all_versions": 90117,
    "num_pmh_records": 163364,
    "num_pages_with_matches": 549026,
    "num_matching_pages_with_fulltext": 72049
  },
  {
    "endpoint_id": "d672cbfea5e69301088",
    "institution_name": "Vancouver Island University Library",
    "repo_name": "VIUSpace",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://viurrspace.ca/oai/request",
    "most_recent_year_harvested": "2019-01-23 5:30:55",
    "request_id": "3f665f",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 315,
    "submittedVersion": 590,
    "all_versions": 905,
    "num_pmh_records": 4930,
    "num_pages_with_matches": 5152,
    "num_matching_pages_with_fulltext": 184
  },
  {
    "endpoint_id": "70da7c8c33d8492cf2e",
    "institution_name": "Institute of Nuclear Sciences \"Vinča",
    "repo_name": "VinaR - Repository of the Vinča Nuclear Institute",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://vinar.vin.bg.ac.rs/oai/request",
    "most_recent_year_harvested": "2019-01-22 17:07:46",
    "request_id": "9df577",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 702,
    "submittedVersion": 4155,
    "all_versions": 4857,
    "num_pmh_records": 7805,
    "num_pages_with_matches": 6153,
    "num_matching_pages_with_fulltext": 1045
  },
  {
    "endpoint_id": "bc1a999cd87a7b7f690",
    "institution_name": "University of New South Wales, Sydney, Australia",
    "repo_name": "UNSWorks",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://unsworks.unsw.edu.au/oai/provider",
    "most_recent_year_harvested": "2019-01-22 0:53:49",
    "request_id": "0eacad",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 1350,
    "submittedVersion": 5645,
    "all_versions": 6995,
    "num_pmh_records": 33553,
    "num_pages_with_matches": 19332,
    "num_matching_pages_with_fulltext": 1446
  },
  {
    "endpoint_id": "003e468747292065231",
    "institution_name": "University of Lapland",
    "repo_name": "LaCRIS - University of Lapland Current Research System",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://lacris.ulapland.fi/ws/oai",
    "most_recent_year_harvested": "2019-01-22 23:47:15",
    "request_id": "c4749d",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 175,
    "submittedVersion": 295,
    "all_versions": 470,
    "num_pmh_records": 8876,
    "num_pages_with_matches": 2314,
    "num_matching_pages_with_fulltext": 163
  },
  {
    "endpoint_id": "3ba687452a47e90aa9f",
    "institution_name": "University of Groningen / Centre for Information Technology",
    "repo_name": "University of Groningen research database",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://pure.rug.nl/ws/oai",
    "most_recent_year_harvested": "2019-01-22 15:50:46",
    "request_id": "7a025c",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 120468,
    "submittedVersion": 112857,
    "all_versions": 233325,
    "num_pmh_records": 148946,
    "num_pages_with_matches": 803713,
    "num_matching_pages_with_fulltext": 273936
  },
  {
    "endpoint_id": "fca05c1d3b6663f6761",
    "institution_name": "University of Eastern Finland",
    "repo_name": "UEF eRepository",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://erepo.uef.fi/oai/request",
    "most_recent_year_harvested": "2019-01-22 10:18:08",
    "request_id": "6ca3df",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 8050,
    "submittedVersion": 4740,
    "all_versions": 12790,
    "num_pmh_records": 4092,
    "num_pages_with_matches": 5807,
    "num_matching_pages_with_fulltext": 2610
  },
  {
    "endpoint_id": "1dd94c25a72c5bdb1f3",
    "institution_name": "University of Toronto",
    "repo_name": "TSpace",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://tspace.library.utoronto.ca/oai/request",
    "most_recent_year_harvested": "2019-01-23 14:14:32",
    "request_id": "c8d466",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 60130,
    "submittedVersion": 80364,
    "all_versions": 140494,
    "num_pmh_records": 80543,
    "num_pages_with_matches": 152484,
    "num_matching_pages_with_fulltext": 38574
  },
  {
    "endpoint_id": "e5971820d7236f12a25",
    "institution_name": "The University of Arizona",
    "repo_name": "UA Campus Repository",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://repository.arizona.edu/oai/request",
    "most_recent_year_harvested": "2019-01-23 2:46:50",
    "request_id": "77fe8e",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 11440,
    "submittedVersion": 11985,
    "all_versions": 23425,
    "num_pmh_records": 67475,
    "num_pages_with_matches": 5097,
    "num_matching_pages_with_fulltext": 4683
  },
  {
    "endpoint_id": "b659fa261dc1f5236fc",
    "institution_name": "Texas A&M University Libraries",
    "repo_name": "OakTrust",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://oaktrust.library.tamu.edu/dspace-oai/request",
    "most_recent_year_harvested": "2019-01-21 22:35:23",
    "request_id": "ae3764",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 6085,
    "submittedVersion": 6333,
    "all_versions": 12418,
    "num_pmh_records": 82475,
    "num_pages_with_matches": 62849,
    "num_matching_pages_with_fulltext": 2481
  },
  {
    "endpoint_id": "af996282fc145250b19",
    "institution_name": "Gettysburg College",
    "repo_name": "The Cupola: Scholarship at Gettysburg College",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://cupola.gettysburg.edu/do/oai/",
    "most_recent_year_harvested": "2019-01-23 1:50:45",
    "request_id": "84efa4",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 460,
    "submittedVersion": 1040,
    "all_versions": 1500,
    "num_pmh_records": 7154,
    "num_pages_with_matches": 878,
    "num_matching_pages_with_fulltext": 583
  },
  {
    "endpoint_id": "0e022feedbb64b085aa",
    "institution_name": "Swansea University",
    "repo_name": "Cronfa",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://cronfa.swan.ac.uk/OAI/Server",
    "most_recent_year_harvested": "2019-01-22 23:42:14",
    "request_id": "f78094",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 11957,
    "submittedVersion": 41512,
    "all_versions": 53469,
    "num_pmh_records": 34801,
    "num_pages_with_matches": 56906,
    "num_matching_pages_with_fulltext": 20592
  },
  {
    "endpoint_id": "e8c54fdc274bf742c01",
    "institution_name": "National University of Singapore",
    "repo_name": "ScholarBank@NUS",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://scholarbank.nus.edu.sg/oai/request",
    "most_recent_year_harvested": "2016-01-01 0:00:00",
    "request_id": "2b338f",
    "error": "error in safe_get_next_record; try again",
    "acceptedVersion": "",
    "publishedVersion": 70,
    "submittedVersion": 1090,
    "all_versions": 1160,
    "num_pmh_records": 42174,
    "num_pages_with_matches": 29308,
    "num_matching_pages_with_fulltext": 252
  },
  {
    "endpoint_id": "5c82d0633d943c165cc",
    "institution_name": "RWTH Aachen",
    "repo_name": "RWTH Publications",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://publications.rwth-aachen.de/oai2d",
    "most_recent_year_harvested": "2018-10-24 23:37:44",
    "request_id": "f6e339",
    "error": "error in get_pmh_input_record: error in get_pmh_input_record: ReadTimeout HTTPConnectionPool(host='publications.rwth-aachen.de', port=80): Read timed out. (read timeout=120) calling None",
    "acceptedVersion": "",
    "publishedVersion": 5236,
    "submittedVersion": 5231,
    "all_versions": 10467,
    "num_pmh_records": 20967,
    "num_pages_with_matches": 21060,
    "num_matching_pages_with_fulltext": 3556
  },
  {
    "endpoint_id": "9d75f894a80ea5396d3",
    "institution_name": "Università degli studi di Milano",
    "repo_name": "Riviste UNIMI",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://riviste.unimi.it/oai",
    "most_recent_year_harvested": "2019-01-22 19:42:10",
    "request_id": "76d489",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 9,
    "submittedVersion": 120,
    "all_versions": 129,
    "num_pmh_records": 7387,
    "num_pages_with_matches": 34,
    "num_matching_pages_with_fulltext": 34
  },
  {
    "endpoint_id": "473b11c32060542d742",
    "institution_name": "Universitat Politècnica de València",
    "repo_name": "RiuNet",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://riunet.upv.es/oai/request",
    "most_recent_year_harvested": "2019-01-23 11:29:59",
    "request_id": "291cdf",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 15330,
    "submittedVersion": 122924,
    "all_versions": 138254,
    "num_pmh_records": 81062,
    "num_pages_with_matches": 83257,
    "num_matching_pages_with_fulltext": 29065
  },
  {
    "endpoint_id": "fe4fe812bff6bdcd493",
    "institution_name": "RCAAP Project by FCT - Portuguese National Funding Agency for Science, Research and Technology",
    "repo_name": "RCAAP Search Portal",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://www.rcaap.pt/oai/request",
    "most_recent_year_harvested": "2018-01-01 0:00:00",
    "request_id": "c26439",
    "error": "",
    "acceptedVersion": 15,
    "publishedVersion": 63134,
    "submittedVersion": 696676,
    "all_versions": 759825,
    "num_pmh_records": 527056,
    "num_pages_with_matches": 412842,
    "num_matching_pages_with_fulltext": 239546
  },
  {
    "endpoint_id": "7c5e73a815d10367bbf",
    "institution_name": "Institute of Architecture and Urban & Spatial Planning of Serbia",
    "repo_name": "RAUmPlan - Repository of Architecture, Urbanism and Planning",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://raumplan.iaus.ac.rs/oai/request",
    "most_recent_year_harvested": "2019-01-22 15:49:10",
    "request_id": "91a330",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 5,
    "submittedVersion": 600,
    "all_versions": 605,
    "num_pmh_records": 319,
    "num_pages_with_matches": 151,
    "num_matching_pages_with_fulltext": 125
  },
  {
    "endpoint_id": "2ce5035dd8b17601a47",
    "institution_name": "Deutsches Elektronen-Synchrotron",
    "repo_name": "DESY Publication Database (PUBDB)",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://bib-pubdb1.desy.de/oai2d",
    "most_recent_year_harvested": "2019-01-23 2:52:53",
    "request_id": "36ad97",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 549,
    "submittedVersion": 813,
    "all_versions": 1362,
    "num_pmh_records": 756,
    "num_pages_with_matches": 921,
    "num_matching_pages_with_fulltext": 348
  },
  {
    "endpoint_id": "7ee32033b87985815a7",
    "institution_name": "University of Calgary",
    "repo_name": "PRISM",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://prism.ucalgary.ca/oai/request",
    "most_recent_year_harvested": "2019-01-23 8:09:08",
    "request_id": "70cca1",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 105,
    "submittedVersion": 120,
    "all_versions": 225,
    "num_pmh_records": 230,
    "num_pages_with_matches": 168,
    "num_matching_pages_with_fulltext": 43
  },
  {
    "endpoint_id": "0990391709d40f75020",
    "institution_name": "University of Potsdam",
    "repo_name": "publish.UP",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://publishup.uni-potsdam.de/oai",
    "most_recent_year_harvested": "2019-01-23 5:29:25",
    "request_id": "c4b659",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 633,
    "submittedVersion": 2912,
    "all_versions": 3545,
    "num_pmh_records": 24230,
    "num_pages_with_matches": 25214,
    "num_matching_pages_with_fulltext": 749
  },
  {
    "endpoint_id": "d01bfa0a179891bdefa",
    "institution_name": "Oslo Metropolitan University",
    "repo_name": "Open Access Journals at Oslo Metropolitan University",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://journals.hioa.no/index.php/index/oai",
    "most_recent_year_harvested": "2019-01-22 23:47:20",
    "request_id": "fb0438",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": 2855,
    "all_versions": 2855,
    "num_pmh_records": 1087,
    "num_pages_with_matches": 689,
    "num_matching_pages_with_fulltext": 686
  },
  {
    "endpoint_id": "ecc903919888a76d5e9",
    "institution_name": "North Carolina State University Libraries",
    "repo_name": "NCSU Libraries Repository",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://repository.lib.ncsu.edu/oai/request",
    "most_recent_year_harvested": "2019-01-22 23:49:09",
    "request_id": "0f6553",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 2515,
    "submittedVersion": 23370,
    "all_versions": 25885,
    "num_pmh_records": 36213,
    "num_pages_with_matches": 5784,
    "num_matching_pages_with_fulltext": 5609
  },
  {
    "endpoint_id": "4e861f823365826e153",
    "institution_name": "University of Belgrade, Institute for Biological Research Sinisa Stankovic",
    "repo_name": "Digital Repository of Archived Publications - Institute for Biological Research Sinisa Stankovic (RADaR)",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://ibiss-r.rcub.bg.ac.rs/oai/request",
    "most_recent_year_harvested": "2019-01-22 23:50:35",
    "request_id": "544ea3",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 629,
    "submittedVersion": 1093,
    "all_versions": 1722,
    "num_pmh_records": 2663,
    "num_pages_with_matches": 2346,
    "num_matching_pages_with_fulltext": 637
  },
  {
    "endpoint_id": "3b0019243f562e6ecd3",
    "institution_name": "SRCE - University of Zagreb University Computing Centre",
    "repo_name": "HRČAK - Portal of scientific journals of Croatia",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://hrcak.srce.hr/oai",
    "most_recent_year_harvested": "2019-01-23 5:31:27",
    "request_id": "a7f462",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 5440,
    "submittedVersion": 50965,
    "all_versions": 56405,
    "num_pmh_records": 126956,
    "num_pages_with_matches": 244324,
    "num_matching_pages_with_fulltext": 22687
  },
  {
    "endpoint_id": "0c2483948fb02b6f303",
    "institution_name": "University of Edinburgh",
    "repo_name": "Edinburgh Research Explorer",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://escholarship.org/oai",
    "most_recent_year_harvested": "2019-01-23 3:36:04",
    "request_id": "e02e74",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 120555,
    "submittedVersion": 279585,
    "all_versions": 400140,
    "num_pmh_records": 215637,
    "num_pages_with_matches": 86554,
    "num_matching_pages_with_fulltext": 80096
  },
  {
    "endpoint_id": "dfdef1a68308d2a866a",
    "institution_name": "University of Massachusetts Medical School",
    "repo_name": "eScholarship@UMMS",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://escholarship.umassmed.edu/do/oai/",
    "most_recent_year_harvested": "2019-01-23 7:39:03",
    "request_id": "bd2a60",
    "error": "",
    "acceptedVersion": 4850,
    "publishedVersion": 14779,
    "submittedVersion": 6346,
    "all_versions": 25975,
    "num_pmh_records": 21705,
    "num_pages_with_matches": 28378,
    "num_matching_pages_with_fulltext": 8327
  },
  {
    "endpoint_id": "0da5f50498c374b13cf",
    "institution_name": "Swinburne University of Technology",
    "repo_name": "Swinburne Research Bank",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://researchbank.swinburne.edu.au/p/oai",
    "most_recent_year_harvested": "2019-01-22 23:14:14",
    "request_id": "55baf1",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 35014,
    "submittedVersion": 24748,
    "all_versions": 59762,
    "num_pmh_records": 58688,
    "num_pages_with_matches": 54087,
    "num_matching_pages_with_fulltext": 12005
  },
  {
    "endpoint_id": "0e4b3470adfe367233a",
    "institution_name": "Swiss Federal Institute of Aquatic Science and Technology (Eawag)",
    "repo_name": "DORA Eawag",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://www.dora.lib4ri.ch/eawag/oai2",
    "most_recent_year_harvested": "2019-01-23 3:49:23",
    "request_id": "ddc81e",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 40,
    "submittedVersion": 65,
    "all_versions": 105,
    "num_pmh_records": 774,
    "num_pages_with_matches": 166,
    "num_matching_pages_with_fulltext": 21
  },
  {
    "endpoint_id": "b2cf508dd15910823cc",
    "institution_name": "Spanish National Research Council (CSIC)",
    "repo_name": "DIGITAL.CSIC",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://digital.csic.es/dspace-oai/request",
    "most_recent_year_harvested": "2019-01-23 7:49:03",
    "request_id": "e7e31c",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 55310,
    "submittedVersion": 257534,
    "all_versions": 312844,
    "num_pmh_records": 98167,
    "num_pages_with_matches": 85242,
    "num_matching_pages_with_fulltext": 62555
  },
  {
    "endpoint_id": "96891e107a54f59202f",
    "institution_name": "Serbian Academy of Sciences and Arts",
    "repo_name": "Digital Archive of SASA",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://dais.sanu.ac.rs/oai/request",
    "most_recent_year_harvested": "2019-01-22 23:42:17",
    "request_id": "c32c95",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 193,
    "submittedVersion": 5018,
    "all_versions": 5211,
    "num_pmh_records": 4504,
    "num_pages_with_matches": 2264,
    "num_matching_pages_with_fulltext": 1428
  },
  {
    "endpoint_id": "f3d4f293b0aeff442d8",
    "institution_name": "University of Colorado Boulder",
    "repo_name": "CU Scholar",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://scholar.colorado.edu/do/oai/",
    "most_recent_year_harvested": "2019-01-22 23:56:42",
    "request_id": "0500b9",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 1895,
    "submittedVersion": 3109,
    "all_versions": 5004,
    "num_pmh_records": 9617,
    "num_pages_with_matches": 1949,
    "num_matching_pages_with_fulltext": 1796
  },
  {
    "endpoint_id": "cc943137faf67e9612e",
    "institution_name": "Cranfield University",
    "repo_name": "CERES",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://dspace.lib.cranfield.ac.uk/oai/request",
    "most_recent_year_harvested": "2019-01-22 23:42:21",
    "request_id": "a366e1",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 7429,
    "submittedVersion": 28331,
    "all_versions": 35760,
    "num_pmh_records": 9967,
    "num_pages_with_matches": 7825,
    "num_matching_pages_with_fulltext": 7178
  },
  {
    "endpoint_id": "3740b7d59b831d2a00d",
    "institution_name": "University of Trieste https://www.units.it/",
    "repo_name": "ArTS Archivio della ricerca di Trieste",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://arts.units.it/oai/request",
    "most_recent_year_harvested": "2019-01-23 3:47:06",
    "request_id": "77963b",
    "error": "",
    "acceptedVersion": 5,
    "publishedVersion": 3700,
    "submittedVersion": 4466,
    "all_versions": 8171,
    "num_pmh_records": 58709,
    "num_pages_with_matches": 21441,
    "num_matching_pages_with_fulltext": 2050
  },
  {
    "endpoint_id": "4d5f97338516bd8a953",
    "institution_name": "Ifremer",
    "repo_name": "Archimer",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://www.ifremer.fr/docelec/oai/OAIHandler",
    "most_recent_year_harvested": "2019-01-22 17:09:45",
    "request_id": "c8fd32",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 17881,
    "submittedVersion": 10310,
    "all_versions": 28191,
    "num_pmh_records": 18970,
    "num_pages_with_matches": 11560,
    "num_matching_pages_with_fulltext": 11374
  },
  {
    "endpoint_id": "c07c82e53deefbbbc3c",
    "institution_name": "Australian Catholic University",
    "repo_name": "Research Bank",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "http://researchbank.acu.edu.au/do/oai/",
    "most_recent_year_harvested": "2019-01-23 7:57:29",
    "request_id": "5f4454",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 4187,
    "submittedVersion": 1971,
    "all_versions": 6158,
    "num_pmh_records": 16700,
    "num_pages_with_matches": 16510,
    "num_matching_pages_with_fulltext": 2139
  },
  {
    "endpoint_id": "5c8a7c638626957bb2b",
    "institution_name": "Verbundzentrale Göttingen (VZG)",
    "repo_name": "Digitale Bibliothek Braunschweig",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "success",
    "pmh_url": "https://publikationsserver.tu-braunschweig.de/servlets/OAIDataProvider",
    "most_recent_year_harvested": "2019-01-22 21:57:42",
    "request_id": "6b5e66",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 467,
    "submittedVersion": 1657,
    "all_versions": 2124,
    "num_pmh_records": 16734,
    "num_pages_with_matches": 1762,
    "num_matching_pages_with_fulltext": 1319
  },
  {
    "endpoint_id": "2f9fd54da3c4f9dbcfa",
    "institution_name": "University of Dayton",
    "repo_name": "eCommons",
    "harvest_identify_response": "error, no pmh_url given",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "",
    "most_recent_year_harvested": "",
    "request_id": "0b7058",
    "error": "Other exception in set_identify_info: argument of type 'NoneType' is not iterable",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "771fac29aef5784a6ba",
    "institution_name": "University of Nebraska-Lincoln",
    "repo_name": "UNL DigitalCommons",
    "harvest_identify_response": "error, no pmh_url given",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "",
    "most_recent_year_harvested": "",
    "request_id": 245305,
    "error": "Other exception in set_identify_info: argument of type 'NoneType' is not iterable",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "4ae09a556d973954a37",
    "institution_name": "Chitkara University",
    "repo_name": "D- space",
    "harvest_identify_response": "error, no pmh_url given",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "",
    "most_recent_year_harvested": "",
    "request_id": "acd371",
    "error": "Other exception in set_identify_info: argument of type 'NoneType' is not iterable",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "f74ae8f4b9a54f7e7d3",
    "institution_name": "University of Western Australia",
    "repo_name": "UWA Research Repository",
    "harvest_identify_response": "error, no pmh_url given",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "",
    "most_recent_year_harvested": "",
    "request_id": "fdeea1",
    "error": "Other exception in set_identify_info: argument of type 'NoneType' is not iterable",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "31d64fa85a5f9b1b295",
    "institution_name": "Bangor University",
    "repo_name": "Bangor University Research Portal",
    "harvest_identify_response": "error, no pmh_url given",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "",
    "most_recent_year_harvested": "",
    "request_id": "0b1c53",
    "error": "Other exception in set_identify_info: argument of type 'NoneType' is not iterable",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "5977ed9fddb72a7b285",
    "institution_name": "Unibo",
    "repo_name": "Unibo",
    "harvest_identify_response": "error in calling identify: SSLError HTTPSConnectionPool(host='www.minervamedica.it', port=443): Max retries exceeded with url: /it/riviste/sports-med-physical-fitness/articolo.php?cod=R40Y2009N03A0297&acquista=1?verb=Identify (Caused by SSLError(SSLError(\"bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)\",),)) calling None",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "https://www.minervamedica.it/it/riviste/sports-med-physical-fitness/articolo.php?cod=R40Y2009N03A0297&acquista=1",
    "most_recent_year_harvested": "2019-01-13 8:18:18",
    "request_id": "c37315",
    "error": "RequestException in set_identify_info: HTTPSConnectionPool(host='www.minervamedica.it', port=443): Max retries exceeded with url: /it/riviste/sports-med-physical-fitness/articolo.php?cod=R40Y2009N03A0297&acquista=1?verb=Identify (Caused by SSLError(SSLError(\"bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)\",),))",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "cf63d82295e011522eb",
    "institution_name": "Saarland University and State Library",
    "repo_name": "SciDok",
    "harvest_identify_response": "error in calling identify: SSLError HTTPSConnectionPool(host='publikationen.sulb.uni-saarland.de', port=443): Max retries exceeded with url: /oai/request?verb=Identify (Caused by SSLError(SSLError(\"bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)\",),)) calling None",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "https://publikationen.sulb.uni-saarland.de/oai/request",
    "most_recent_year_harvested": "2019-01-14 15:35:44",
    "request_id": None,
    "error": "RequestException in set_identify_info",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "e93ebca03961ed96201",
    "institution_name": "Roskilde University",
    "repo_name": "RUCforsk",
    "harvest_identify_response": "error in calling identify: HTTPError 405 Client Error: 405 for url: https://rucforsk.ruc.dk/ws/OAI/request?verb=Identify calling https://rucforsk.ruc.dk/ws/OAI/request?verb=Identify",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "https://rucforsk.ruc.dk/ws/OAI/request",
    "most_recent_year_harvested": "2019-01-14 15:37:55",
    "request_id": "a747e3",
    "error": "RequestException in set_identify_info",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "d6343113e33de95bc3d",
    "institution_name": "University of Kentucky",
    "repo_name": "UKnowledge",
    "harvest_identify_response": "error in calling identify: HTTPError 404 Client Error: Not Found for url: https://uknowledge.uky.edu/do/oai/%20?verb=Identify calling https://uknowledge.uky.edu/do/oai/%20?verb=Identify",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "http://uknowledge.uky.edu/do/oai/",
    "most_recent_year_harvested": "2019-01-14 15:39:38",
    "request_id": "0b61f1",
    "error": "RequestException in set_identify_info: 404 Client Error: Not Found for url: https://uknowledge.uky.edu/do/oai/%20?verb=Identify",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "beb384735c50f7cdb77",
    "institution_name": "Copenhagen Business School",
    "repo_name": "Research@CBS",
    "harvest_identify_response": "error in calling identify: HTTPError 404 Client Error: Not Found for url: https://research.cbs.dk/ws/oai?verb=Identify calling https://research.cbs.dk/ws/oai?verb=Identify",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "http://research.cbs.dk/ws/oai",
    "most_recent_year_harvested": "2019-01-14 20:52:16",
    "request_id": "832ef7",
    "error": "RequestException in set_identify_info",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "b016e2424db52f0f336",
    "institution_name": "Coventry University",
    "repo_name": "Pure",
    "harvest_identify_response": "error in calling identify: HTTPError 404 Client Error: Not Found for url: https://pureportal.coventry.ac.uk/ws/OAIHandler?verb=Identify calling https://pureportal.coventry.ac.uk/ws/OAIHandler?verb=Identify",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "http://pureportal.coventry.ac.uk/ws/OAIHandler",
    "most_recent_year_harvested": "2019-01-14 15:35:42",
    "request_id": "3cf74a",
    "error": "RequestException in set_identify_info",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "fb8535628584dd2bfbf",
    "institution_name": "Universitätsbibliothek Freiburg",
    "repo_name": "FreiDok plus",
    "harvest_identify_response": "error in calling identify: HTTPError 404 Client Error: Not Found for url: https://freidok.uni-freiburg.de/error/HTTP_NOT_FOUND.html.var calling https://freidok.uni-freiburg.de/error/HTTP_NOT_FOUND.html.var",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "http://freidok.uni-freiburg.de/oai2/oai2.php",
    "most_recent_year_harvested": "2019-01-13 23:51:27",
    "request_id": "3e2a19",
    "error": "RequestException in set_identify_info",
    "acceptedVersion": "",
    "publishedVersion": 4705,
    "submittedVersion": 12999,
    "all_versions": 17704,
    "num_pmh_records": 13023,
    "num_pages_with_matches": 45949,
    "num_matching_pages_with_fulltext": 3541
  },
  {
    "endpoint_id": "a34918de3714416c40b",
    "institution_name": "Forschungszentrum Jülich",
    "repo_name": "JuSER",
    "harvest_identify_response": "error in calling identify: HTTPError 404 Client Error: Not Found for url: http://juser.fz-juelich.de/oai2d%20?verb=Identify calling http://juser.fz-juelich.de/oai2d%20?verb=Identify",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "http://juser.fz-juelich.de/oai2d",
    "most_recent_year_harvested": "2019-01-14 1:19:14",
    "request_id": "0231be",
    "error": "RequestException in set_identify_info",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "75669c212500b97833d",
    "institution_name": "The University of Melbourne",
    "repo_name": "Minerva Access",
    "harvest_identify_response": "error in calling identify: HTTPError 400 Client Error: Bad Request for url: https://minerva-access.unimelb.edu.au/oai#?verb=Identify calling https://minerva-access.unimelb.edu.au/oai#?verb=Identify",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "https://minerva-access.unimelb.edu.au/oai#",
    "most_recent_year_harvested": "2019-01-14 15:48:42",
    "request_id": "90b1d4",
    "error": "RequestException in set_identify_info: 400 Client Error: Bad Request for url: https://minerva-access.unimelb.edu.au/oai#?verb=Identify",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "30db36b7afef9c578c4",
    "institution_name": "University of Southern Denmark",
    "repo_name": "University of Southern Denmark Research Portal",
    "harvest_identify_response": "error in calling identify: ConnectionError ('Connection aborted.', BadStatusLine(\"''\",)) calling None",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "http://findresearcher.sdu.dk:8443/ws/oai/request",
    "most_recent_year_harvested": "",
    "request_id": "66c44e",
    "error": "RequestException in set_identify_info",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "0f036e06c5b2a785164",
    "institution_name": "Science Trends",
    "repo_name": "Science Trends Feed",
    "harvest_identify_response": "error in calling identify: AttributeError 'NoneType' object has no attribute 'group' calling https://sciencetrends.com/feed/?verb=Identify",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "http://sciencetrends.com/feed",
    "most_recent_year_harvested": "2019-01-14 15:35:27",
    "request_id": 926193,
    "error": "AttributeError in set_identify_info.",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "d66f931e34ca8fdc456",
    "institution_name": "Centro Hospitalar e Universitário de Coimbra",
    "repo_name": "Repositório Institucional dos Hospitais da Universidade de Coimbra (RIHUC)",
    "harvest_identify_response": "error in calling identify: AttributeError 'NoneType' object has no attribute 'group' calling http://rihuc.huc.min-saude.pt/?verb=Identify",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "http://rihuc.huc.min-saude.pt/",
    "most_recent_year_harvested": "2019-01-14 15:44:05",
    "request_id": "c3e0c0",
    "error": "AttributeError in set_identify_info.",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "252b9df12525627d369",
    "institution_name": "Aarhus University",
    "repo_name": "Aarhus University",
    "harvest_identify_response": "error in calling identify: AttributeError 'NoneType' object has no attribute 'findall' calling http://www.atira.dk/en/pure/ calling http://www.atira.dk/en/pure/",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "http://pure.atira.dk",
    "most_recent_year_harvested": "2019-01-14 20:52:20",
    "request_id": "77f41c",
    "error": "AttributeError in set_identify_info.",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "a8c94ce6c44f6f33f50",
    "institution_name": "University of Oklahoma",
    "repo_name": "Theatre Organ: Journal of the American Theatre Organ Society",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "https://theatreorgan.shareok.org/theatreorgan/oai",
    "most_recent_year_harvested": "2019-01-22 23:42:13",
    "request_id": "6888b9",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 66,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "0dde28a908329849966",
    "institution_name": "Berlin-Brandenburg Academy of Sciences and Humanities",
    "repo_name": "CLARIN service center of the Zentrum Sprache at the BBAW",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "no pmh_input_records returned",
    "pmh_url": "https://clarin.bbaw.de:8088/oaiprovider",
    "most_recent_year_harvested": "2019-01-22 17:09:45",
    "request_id": "63f2fe",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 4612,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "4dd7e55a5e7905ae415",
    "institution_name": "Université d'Angers",
    "repo_name": "Okina",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "error in get_pmh_input_record: HTTPError 500 Server Error: Service unavailable (with message) for url: http://okina.univ-angers.fr/oai?until=2019-01-17&verb=ListRecords&metadataPrefix=oai_dc&from=2018-12-18 calling http://okina.univ-angers.fr/oai?until=2019-01-17&verb=ListRecords&metadataPrefix=oai_dc&from=2018-12-18",
    "pmh_url": "http://okina.univ-angers.fr/oai",
    "most_recent_year_harvested": "2002-01-01 0:00:00",
    "request_id": "e38de9",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "eea8ce709d778a589a8",
    "institution_name": "Kyushu University",
    "repo_name": "Kyushu University Institutional Repository (QIR)",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "error in get_pmh_input_record: CannotDisseminateFormat  calling http://catalog.lib.kyushu-u.ac.jp/mmd/mmd_api/oai-pmh/?verb=ListRecords&from=2018-12-18&metadataPrefix=oai_dc&until=2019-01-17",
    "pmh_url": "http://catalog.lib.kyushu-u.ac.jp/mmd/mmd_api/oai-pmh/",
    "most_recent_year_harvested": "2001-01-01 0:00:00",
    "request_id": "1b1c71",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "9309be00b4e3315c846",
    "institution_name": "Brock University",
    "repo_name": "Brock University Digital Repository",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "error in get_pmh_input_record: BadArgument Invalid date given in until parameter calling https://dr.library.brocku.ca/oai/request?until=2019-01-17&verb=ListRecords&metadataPrefix=oai_dc&from=2018-12-18",
    "pmh_url": "https://dr.library.brocku.ca/oai/request",
    "most_recent_year_harvested": "2001-01-01 0:00:00",
    "request_id": "3a64e1",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "2da9fa5705c80b7875b",
    "institution_name": "University of Michigan",
    "repo_name": "Deep Blue",
    "harvest_identify_response": "success",
    "harvest_test_recent_dates": "error in get_pmh_input_record: BadArgument Invalid date given in until parameter calling https://deepblue.lib.umich.edu/dspace-oai/request?verb=ListRecords&from=2018-12-18&metadataPrefix=oai_dc&until=2019-01-17",
    "pmh_url": "http://deepblue.lib.umich.edu/dspace-oai/request",
    "most_recent_year_harvested": "2001-01-01 0:00:00",
    "request_id": "d5009b",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  },
  {
    "endpoint_id": "d490f2816cb229e8932",
    "institution_name": "University of West London",
    "repo_name": "UWL Repository",
    "harvest_identify_response": "",
    "harvest_test_recent_dates": "",
    "pmh_url": "https://repository.uwl.ac.uk/cgi/oai2",
    "most_recent_year_harvested": "2019-01-22 16:40:37",
    "request_id": "e8159f",
    "error": "",
    "acceptedVersion": "",
    "publishedVersion": 1208,
    "submittedVersion": 3845,
    "all_versions": 5053,
    "num_pmh_records": 3543,
    "num_pages_with_matches": 2608,
    "num_matching_pages_with_fulltext": 1018
  },
  {
    "endpoint_id": "b525a985fdd7ae5521f",
    "institution_name": "University of Belgrade, Vinca Institute of Nuclear Sciences",
    "repo_name": "VinaR - Repository of the Vinca Nuclear Institute",
    "harvest_identify_response": "",
    "harvest_test_recent_dates": "",
    "pmh_url": "http://vinar.vin.bg.ac.rs/oai",
    "most_recent_year_harvested": "",
    "request_id": "ec87e5",
    "error": "error in get_pmh_input_record: error in get_pmh_input_record: HTTPError 400 Client Error: Bad Request for url: http://vinar.vin.bg.ac.rs/oai?verb=ListRecords&from=1999-12-31&metadataPrefix=oai_dc&until=2001-01-01 calling http://vinar.vin.bg.ac.rs/oai?verb=ListRecords&from=1999-12-31&metadataPrefix=oai_dc&until=2001-01-01",
    "acceptedVersion": "",
    "publishedVersion": "",
    "submittedVersion": "",
    "all_versions": 0,
    "num_pmh_records": 0,
    "num_pages_with_matches": 0,
    "num_matching_pages_with_fulltext": 0
  }
]