map_mendeley_countries = {
    u'Korea (South)': "South Korea",
    u'Serbia and Montenegro': "Serbia",
    u'Republic of Singapore': "Singapore",
    u'Fiji Islands': "Fiji",
    u'Reunion': "French Southern Territories",
    u'Saint Vincent and The Grenadines': "Saint Vincent and the Grenadines"
}

def get_name_from_iso(iso_name):
    for country_name, country_dict in country_info.iteritems():
        if iso_name == country_dict["iso"]:
            return country_name
    return None

# iso from countries_info.py in impactstory classic
# global south info from https://meta.wikimedia.org/wiki/List_of_countries_by_regional_classification
# pacific rim info from https://en.wikipedia.org/wiki/Pacific_Rim
country_info = {
     'Afghanistan': {'is_global_south': True,
                     'iso': 'AF',
                     'region': 'Asia & Pacific'},
     'Aland Islands': {'is_global_south': False, 'iso': 'AX', 'region': 'Europe'},
     'Albania': {'is_global_south': False, 'iso': 'AL', 'region': 'Europe'},
     'Algeria': {'is_global_south': True, 'iso': 'DZ', 'region': 'Arab States'},
     'American Samoa': {'is_global_south': True,
                        'iso': 'AS',
                        'region': 'Asia & Pacific'},
     'Andorra': {'is_global_south': False, 'iso': 'AD', 'region': 'Europe'},
     'Angola': {'is_global_south': True, 'iso': 'AO', 'region': 'Africa'},
     'Anguilla': {'is_global_south': True,
                  'iso': 'AI',
                  'region': 'South/Latin America'},
     'Antarctica': {'is_global_south': True, 'iso': 'AQ', 'region': 'Asia & Pacific'},
     'Antigua and Barbuda': {'is_global_south': True,
                             'iso': 'AG',
                             'region': 'South/Latin America'},
     'Argentina': {'is_global_south': True,
                   'iso': 'AR',
                   'region': 'South/Latin America'},
     'Armenia': {'is_global_south': True, 'iso': 'AM', 'region': 'CIS'},
     'Aruba': {'is_global_south': True, 'iso': 'AW', 'region': 'South/Latin America'},
     'Australia': {'is_global_south': False, 'iso': 'AU', 'region': 'Asia & Pacific'},
     'Austria': {'is_global_south': False, 'iso': 'AT', 'region': 'Europe'},
     'Azerbaijan': {'is_global_south': True, 'iso': 'AZ', 'region': 'CIS'},
     'Bahamas': {'is_global_south': True,
                 'iso': 'BS',
                 'region': 'South/Latin America'},
     'Bahrain': {'is_global_south': True, 'iso': 'BH', 'region': 'Arab States'},
     'Bangladesh': {'is_global_south': True, 'iso': 'BD', 'region': 'Asia & Pacific'},
     'Barbados': {'is_global_south': True,
                  'iso': 'BB',
                  'region': 'South/Latin America'},
     'Belarus': {'is_global_south': True, 'iso': 'BY', 'region': 'CIS'},
     'Belgium': {'is_global_south': False, 'iso': 'BE', 'region': 'Europe'},
     'Belize': {'is_global_south': True,
                'iso': 'BZ',
                'region': 'South/Latin America'},
     'Benin': {'is_global_south': True, 'iso': 'BJ', 'region': 'Africa'},
     'Bermuda': {'is_global_south': False, 'iso': 'BM', 'region': 'North America'},
     'Bhutan': {'is_global_south': True, 'iso': 'BT', 'region': 'Asia & Pacific'},
     'Bolivia': {'is_global_south': True,
                 'iso': 'BO',
                 'region': 'South/Latin America'},
     'Bosnia and Herzegovina': {'is_global_south': False,
                                'iso': 'BA',
                                'region': 'Europe'},
     'Botswana': {'is_global_south': True, 'iso': 'BW', 'region': 'Africa'},
     'Bouvet Island': {'is_global_south': True,
                       'iso': 'BV',
                       'region': 'South/Latin America'},
     'Brazil': {'is_global_south': True,
                'iso': 'BR',
                'region': 'South/Latin America'},
     'British Indian Ocean Territory': {'is_global_south': True,
                                        'iso': 'IO',
                                        'region': 'Asia & Pacific'},
     'British Virgin Islands': {'is_global_south': True,
                                'iso': 'VG',
                                'region': 'South/Latin America'},
     'Brunei': {'is_global_south': True, 'iso': 'BN', 'region': 'Asia & Pacific'},
     'Bulgaria': {'is_global_south': False, 'iso': 'BG', 'region': 'Europe'},
     'Burkina Faso': {'is_global_south': True, 'iso': 'BF', 'region': 'Africa'},
     'Burundi': {'is_global_south': True, 'iso': 'BI', 'region': 'Africa'},
     'Cambodia': {'is_global_south': True, 'iso': 'KH', 'region': 'Asia & Pacific'},
     'Cameroon': {'is_global_south': True, 'iso': 'CM', 'region': 'Africa'},
     'Canada': {'is_global_south': False, 'iso': 'CA', 'region': 'North America'},
     'Cape Verde': {'is_global_south': True, 'iso': 'CV', 'region': 'Africa'},
     'Cayman Islands': {'is_global_south': True,
                        'iso': 'KY',
                        'region': 'South/Latin America'},
     'Central African Republic': {'is_global_south': True,
                                  'iso': 'CF',
                                  'region': 'Africa'},
     'Chad': {'is_global_south': True, 'iso': 'TD', 'region': 'Africa'},
     'Chile': {'is_global_south': True, 'iso': 'CL', 'region': 'South/Latin America'},
     'China': {'is_global_south': True, 'iso': 'CN', 'region': 'Asia & Pacific'},
     'Christmas Island': {'is_global_south': True,
                          'iso': 'CX',
                          'region': 'Asia & Pacific'},
     'Cocos (Keeling) Islands': {'is_global_south': True,
                                 'iso': 'CC',
                                 'region': 'Asia & Pacific'},
     'Colombia': {'is_global_south': True,
                  'iso': 'CO',
                  'region': 'South/Latin America'},
     'Comoros': {'is_global_south': True, 'iso': 'KM', 'region': 'Arab States'},
     'Cook Islands': {'is_global_south': True,
                      'iso': 'CK',
                      'region': 'Asia & Pacific'},
     'Costa Rica': {'is_global_south': True,
                    'iso': 'CR',
                    'region': 'South/Latin America'},
     "Cote D'Ivoire": {'is_global_south': True, 'iso': 'CI', 'region': 'Africa'},
     'Croatia': {'is_global_south': False, 'iso': 'HR', 'region': 'Europe'},
     'Cuba': {'is_global_south': True, 'iso': 'CU', 'region': 'South/Latin America'},
     'Cyprus': {'is_global_south': False, 'iso': 'CY', 'region': 'Europe'},
     'Czech Republic': {'is_global_south': False, 'iso': 'CZ', 'region': 'Europe'},
     'DR Congo': {'is_global_south': True, 'iso': 'CD', 'region': 'Africa'},
     'Denmark': {'is_global_south': False, 'iso': 'DK', 'region': 'Europe'},
     'Djibouti': {'is_global_south': True, 'iso': 'DJ', 'region': 'Arab States'},
     'Dominica': {'is_global_south': True,
                  'iso': 'DM',
                  'region': 'South/Latin America'},
     'Dominican Republic': {'is_global_south': True,
                            'iso': 'DO',
                            'region': 'South/Latin America'},
     'Ecuador': {'is_global_south': True,
                 'iso': 'EC',
                 'region': 'South/Latin America'},
     'Egypt': {'is_global_south': True, 'iso': 'EG', 'region': 'Arab States'},
     'El Salvador': {'is_global_south': True,
                     'iso': 'SV',
                     'region': 'South/Latin America'},
     'Equatorial Guinea': {'is_global_south': True, 'iso': 'GQ', 'region': 'Africa'},
     'Eritrea': {'is_global_south': True, 'iso': 'ER', 'region': 'Africa'},
     'Estonia': {'is_global_south': False, 'iso': 'EE', 'region': 'Europe'},
     'Ethiopia': {'is_global_south': True, 'iso': 'ET', 'region': 'Africa'},
     'Falkland Islands': {'is_global_south': True,
                          'iso': 'FK',
                          'region': 'South/Latin America'},
     'Faroe Islands': {'is_global_south': False, 'iso': 'FO', 'region': 'Europe'},
     'Fiji': {'is_global_south': True, 'iso': 'FJ', 'region': 'Asia & Pacific'},
     'Finland': {'is_global_south': False, 'iso': 'FI', 'region': 'Europe'},
     'France': {'is_global_south': False, 'iso': 'FR', 'region': 'Europe'},
     'French Guiana': {'is_global_south': True,
                       'iso': 'GF',
                       'region': 'South/Latin America'},
     'French Polynesia': {'is_global_south': True,
                          'iso': 'PF',
                          'region': 'Asia & Pacific'},
     'French Southern Territories': {'is_global_south': True,
                                     'iso': 'TF',
                                     'region': 'Asia & Pacific'},
     'Gabon': {'is_global_south': True, 'iso': 'GA', 'region': 'Africa'},
     'Gambia': {'is_global_south': True, 'iso': 'GM', 'region': 'Africa'},
     'Georgia': {'is_global_south': True, 'iso': 'GE', 'region': 'CIS'},
     'Germany': {'is_global_south': False, 'iso': 'DE', 'region': 'Europe'},
     'Ghana': {'is_global_south': True, 'iso': 'GH', 'region': 'Africa'},
     'Gibraltar': {'is_global_south': False, 'iso': 'GI', 'region': 'Europe'},
     'Greece': {'is_global_south': False, 'iso': 'GR', 'region': 'Europe'},
     'Greenland': {'is_global_south': False, 'iso': 'GL', 'region': 'Europe'},
     'Grenada': {'is_global_south': True,
                 'iso': 'GD',
                 'region': 'South/Latin America'},
     'Guadeloupe': {'is_global_south': True,
                    'iso': 'GP',
                    'region': 'South/Latin America'},
     'Guam': {'is_global_south': True, 'iso': 'GU', 'region': 'Asia & Pacific'},
     'Guatemala': {'is_global_south': True,
                   'iso': 'GT',
                   'region': 'South/Latin America'},
     'Guernsey': {'is_global_south': False, 'iso': 'GG', 'region': 'Europe'},
     'Guinea': {'is_global_south': True, 'iso': 'GN', 'region': 'Africa'},
     'Guinea-Bissau': {'is_global_south': True, 'iso': 'GW', 'region': 'Africa'},
     'Guyana': {'is_global_south': True,
                'iso': 'GY',
                'region': 'South/Latin America'},
     'Haiti': {'is_global_south': True, 'iso': 'HT', 'region': 'South/Latin America'},
     'Heard Island and McDonald Islands': {'is_global_south': True,
                                           'iso': 'HM',
                                           'region': 'Asia & Pacific'},
     'Honduras': {'is_global_south': True,
                  'iso': 'HN',
                  'region': 'South/Latin America'},
     'Hong Kong': {'is_global_south': False, 'iso': 'HK', 'region': 'Asia & Pacific'},
     'Hungary': {'is_global_south': False, 'iso': 'HU', 'region': 'Europe'},
     'Iceland': {'is_global_south': False, 'iso': 'IS', 'region': 'Europe'},
     'India': {'is_global_south': True, 'iso': 'IN', 'region': 'Asia & Pacific'},
     'Indonesia': {'is_global_south': True, 'iso': 'ID', 'region': 'Asia & Pacific'},
     'Iran': {'is_global_south': True, 'iso': 'IR', 'region': 'Asia & Pacific'},
     'Iraq': {'is_global_south': True, 'iso': 'IQ', 'region': 'Arab States'},
     'Ireland': {'is_global_south': False, 'iso': 'IE', 'region': 'Europe'},
     'Isle of Man': {'is_global_south': False, 'iso': 'IM', 'region': 'Europe'},
     'Israel': {'is_global_south': False, 'iso': 'IL', 'region': 'Europe'},
     'Italy': {'is_global_south': False, 'iso': 'IT', 'region': 'Europe'},
     'Jamaica': {'is_global_south': True,
                 'iso': 'JM',
                 'region': 'South/Latin America'},
     'Japan': {'is_global_south': False, 'iso': 'JP', 'region': 'Asia & Pacific'},
     'Jersey': {'is_global_south': False, 'iso': 'JE', 'region': 'Europe'},
     'Jordan': {'is_global_south': True, 'iso': 'JO', 'region': 'Arab States'},
     'Kazakhstan': {'is_global_south': True, 'iso': 'KZ', 'region': 'CIS'},
     'Kenya': {'is_global_south': True, 'iso': 'KE', 'region': 'Africa'},
     'Kiribati': {'is_global_south': True, 'iso': 'KI', 'region': 'Asia & Pacific'},
     'Kuwait': {'is_global_south': True, 'iso': 'KW', 'region': 'Arab States'},
     'Kyrgyzstan': {'is_global_south': True, 'iso': 'KG', 'region': 'CIS'},
     'Laos': {'is_global_south': True, 'iso': 'LA', 'region': 'Asia & Pacific'},
     'Latvia': {'is_global_south': False, 'iso': 'LV', 'region': 'Europe'},
     'Lebanon': {'is_global_south': True, 'iso': 'LB', 'region': 'Arab States'},
     'Lesotho': {'is_global_south': True, 'iso': 'LS', 'region': 'Africa'},
     'Liberia': {'is_global_south': True, 'iso': 'LR', 'region': 'Africa'},
     'Libya': {'is_global_south': True, 'iso': 'LY', 'region': 'Arab States'},
     'Liechtenstein': {'is_global_south': False, 'iso': 'LI', 'region': 'Europe'},
     'Lithuania': {'is_global_south': False, 'iso': 'LT', 'region': 'Europe'},
     'Luxembourg': {'is_global_south': False, 'iso': 'LU', 'region': 'Europe'},
     'Macau': {'is_global_south': False, 'iso': 'MO', 'region': 'Asia & Pacific'},
     'Macedonia': {'is_global_south': False, 'iso': 'MK', 'region': 'Europe'},
     'Madagascar': {'is_global_south': True, 'iso': 'MG', 'region': 'Africa'},
     'Malawi': {'is_global_south': True, 'iso': 'MW', 'region': 'Africa'},
     'Malaysia': {'is_global_south': True, 'iso': 'MY', 'region': 'Asia & Pacific'},
     'Maldives': {'is_global_south': True, 'iso': 'MV', 'region': 'Asia & Pacific'},
     'Mali': {'is_global_south': True, 'iso': 'ML', 'region': 'Africa'},
     'Malta': {'is_global_south': False, 'iso': 'MT', 'region': 'Europe'},
     'Marshall Islands': {'is_global_south': True,
                          'iso': 'MH',
                          'region': 'Asia & Pacific'},
     'Martinique': {'is_global_south': True,
                    'iso': 'MQ',
                    'region': 'South/Latin America'},
     'Mauritania': {'is_global_south': True, 'iso': 'MR', 'region': 'Arab States'},
     'Mauritius': {'is_global_south': True, 'iso': 'MU', 'region': 'Africa'},
     'Mayotte': {'is_global_south': True, 'iso': 'YT', 'region': 'Africa'},
     'Mexico': {'is_global_south': True,
                'iso': 'MX',
                'region': 'South/Latin America'},
     'Micronesia': {'is_global_south': True, 'iso': 'FM', 'region': 'Asia & Pacific'},
     'Moldova': {'is_global_south': False, 'iso': 'MD', 'region': 'Europe'},
     'Monaco': {'is_global_south': False, 'iso': 'MC', 'region': 'Europe'},
     'Mongolia': {'is_global_south': True, 'iso': 'MN', 'region': 'Asia & Pacific'},
     'Montenegro': {'is_global_south': False, 'iso': 'ME', 'region': 'Europe'},
     'Montserrat': {'is_global_south': True,
                    'iso': 'MS',
                    'region': 'South/Latin America'},
     'Morocco': {'is_global_south': True, 'iso': 'MA', 'region': 'Arab States'},
     'Mozambique': {'is_global_south': True, 'iso': 'MZ', 'region': 'Africa'},
     'Myanmar': {'is_global_south': True, 'iso': 'MM', 'region': 'Asia & Pacific'},
     'Namibia': {'is_global_south': True, 'iso': 'NA', 'region': 'Africa'},
     'Nauru': {'is_global_south': True, 'iso': 'NR', 'region': 'Asia & Pacific'},
     'Nepal': {'is_global_south': True, 'iso': 'NP', 'region': 'Asia & Pacific'},
     'Netherlands': {'is_global_south': False, 'iso': 'NL', 'region': 'Europe'},
     'New Caledonia': {'is_global_south': True,
                       'iso': 'NC',
                       'region': 'Asia & Pacific'},
     'New Zealand': {'is_global_south': False,
                     'iso': 'NZ',
                     'region': 'Asia & Pacific'},
     'Nicaragua': {'is_global_south': True,
                   'iso': 'NI',
                   'region': 'South/Latin America'},
     'Niger': {'is_global_south': True, 'iso': 'NE', 'region': 'Africa'},
     'Nigeria': {'is_global_south': True, 'iso': 'NG', 'region': 'Africa'},
     'Niue': {'is_global_south': True, 'iso': 'NU', 'region': 'Asia & Pacific'},
     'Norfolk Island': {'is_global_south': True,
                        'iso': 'NF',
                        'region': 'Asia & Pacific'},
     'North Korea': {'is_global_south': True,
                     'iso': 'KP',
                     'region': 'Asia & Pacific'},
     'Northern Mariana Islands': {'is_global_south': True,
                                  'iso': 'MP',
                                  'region': 'Asia & Pacific'},
     'Norway': {'is_global_south': False, 'iso': 'NO', 'region': 'Europe'},
     'Oman': {'is_global_south': True, 'iso': 'OM', 'region': 'Arab States'},
     'Pakistan': {'is_global_south': True, 'iso': 'PK', 'region': 'Asia & Pacific'},
     'Palau': {'is_global_south': True, 'iso': 'PW', 'region': 'Asia & Pacific'},
     'Palestine': {'is_global_south': True, 'iso': 'PS', 'region': 'Arab States'},
     'Panama': {'is_global_south': True,
                'iso': 'PA',
                'region': 'South/Latin America'},
     'Papua New Guinea': {'is_global_south': True,
                          'iso': 'PG',
                          'region': 'Asia & Pacific'},
     'Paraguay': {'is_global_south': True,
                  'iso': 'PY',
                  'region': 'South/Latin America'},
     'Peru': {'is_global_south': True, 'iso': 'PE', 'region': 'South/Latin America'},
     'Philippines': {'is_global_south': True,
                     'iso': 'PH',
                     'region': 'Asia & Pacific'},
     'Pitcairn Islands': {'is_global_south': True,
                          'iso': 'PN',
                          'region': 'Asia & Pacific'},
     'Poland': {'is_global_south': False, 'iso': 'PL', 'region': 'Europe'},
     'Portugal': {'is_global_south': False, 'iso': 'PT', 'region': 'Europe'},
     'Puerto Rico': {'is_global_south': True,
                     'iso': 'PR',
                     'region': 'South/Latin America'},
     'Qatar': {'is_global_south': True, 'iso': 'QA', 'region': 'Arab States'},
     'Republic of the Congo': {'is_global_south': True,
                               'iso': 'CG',
                               'region': 'Africa'},
     'Romania': {'is_global_south': False, 'iso': 'RO', 'region': 'Europe'},
     'Russia': {'is_global_south': False, 'iso': 'RU', 'region': 'Europe'},
     'Rwanda': {'is_global_south': True, 'iso': 'RW', 'region': 'Africa'},
     'Saint Barthelemy': {'is_global_south': True,
                          'iso': 'BL',
                          'region': 'South/Latin America'},
     'Saint Helena': {'is_global_south': True, 'iso': 'SH', 'region': 'Africa'},
     'Saint Kitts and Nevis': {'is_global_south': True,
                               'iso': 'KN',
                               'region': 'South/Latin America'},
     'Saint Lucia': {'is_global_south': True,
                     'iso': 'LC',
                     'region': 'South/Latin America'},
     'Saint Martin': {'is_global_south': True,
                      'iso': 'MF',
                      'region': 'South/Latin America'},
     'Saint Pierre and Miquelon': {'is_global_south': False,
                                   'iso': 'PM',
                                   'region': 'North America'},
     'Saint Vincent and the Grenadines': {'is_global_south': True,
                                          'iso': 'VC',
                                          'region': 'South/Latin America'},
     'Samoa': {'is_global_south': True, 'iso': 'WS', 'region': 'Asia & Pacific'},
     'San Marino': {'is_global_south': False, 'iso': 'SM', 'region': 'Europe'},
     'Saudi Arabia': {'is_global_south': True, 'iso': 'SA', 'region': 'Arab States'},
     'Senegal': {'is_global_south': True, 'iso': 'SN', 'region': 'Africa'},
     'Serbia': {'is_global_south': False, 'iso': 'RS', 'region': 'Europe'},
     'Seychelles': {'is_global_south': True, 'iso': 'SC', 'region': 'Africa'},
     'Sierra Leone': {'is_global_south': True, 'iso': 'SL', 'region': 'Africa'},
     'Singapore': {'is_global_south': False, 'iso': 'SG', 'region': 'Asia & Pacific'},
     'Slovakia': {'is_global_south': False, 'iso': 'SK', 'region': 'Europe'},
     'Slovenia': {'is_global_south': False, 'iso': 'SI', 'region': 'Europe'},
     'Solomon Islands': {'is_global_south': True,
                         'iso': 'SB',
                         'region': 'Asia & Pacific'},
     'Somalia': {'is_global_south': True, 'iso': 'SO', 'region': 'Arab States'},
     'South Africa': {'is_global_south': True, 'iso': 'ZA', 'region': 'Africa'},
     'South Georgia': {'is_global_south': True,
                       'iso': 'GS',
                       'region': 'South/Latin America'},
     'South Korea': {'is_global_south': False,
                     'iso': 'KR',
                     'region': 'Asia & Pacific'},
     'South Sudan': {'is_global_south': True, 'iso': 'SS', 'region': 'Africa'},
     'Spain': {'is_global_south': False, 'iso': 'ES', 'region': 'Europe'},
     'Sri Lanka': {'is_global_south': True, 'iso': 'LK', 'region': 'Asia & Pacific'},
     'Sudan': {'is_global_south': True, 'iso': 'SD', 'region': 'Arab States'},
     'Suriname': {'is_global_south': True,
                  'iso': 'SR',
                  'region': 'South/Latin America'},
     'Svalbard and Jan Mayen': {'is_global_south': False,
                                'iso': 'SJ',
                                'region': 'Europe'},
     'Swaziland': {'is_global_south': True, 'iso': 'SZ', 'region': 'Africa'},
     'Sweden': {'is_global_south': False, 'iso': 'SE', 'region': 'Europe'},
     'Switzerland': {'is_global_south': False, 'iso': 'CH', 'region': 'Europe'},
     'Syria': {'is_global_south': True, 'iso': 'SY', 'region': 'Asia & Pacific'},
     'Taiwan': {'is_global_south': False, 'iso': 'TW', 'region': 'Asia & Pacific'},
     'Tajikistan': {'is_global_south': True, 'iso': 'TJ', 'region': 'CIS'},
     'Tanzania': {'is_global_south': True, 'iso': 'TZ', 'region': 'Africa'},
     'Thailand': {'is_global_south': True, 'iso': 'TH', 'region': 'Asia & Pacific'},
     'Timor-Leste': {'is_global_south': True,
                     'iso': 'TL',
                     'region': 'Asia & Pacific'},
     'Togo': {'is_global_south': True, 'iso': 'TG', 'region': 'Africa'},
     'Tokelau': {'is_global_south': True, 'iso': 'TK', 'region': 'Asia & Pacific'},
     'Tonga': {'is_global_south': True, 'iso': 'TO', 'region': 'Asia & Pacific'},
     'Trinidad and Tobago': {'is_global_south': True,
                             'iso': 'TT',
                             'region': 'South/Latin America'},
     'Tunisia': {'is_global_south': True, 'iso': 'TN', 'region': 'Arab States'},
     'Turkey': {'is_global_south': False, 'iso': 'TR', 'region': 'Europe'},
     'Turkmenistan': {'is_global_south': True, 'iso': 'TM', 'region': 'CIS'},
     'Turks and Caicos Islands': {'is_global_south': True,
                                  'iso': 'TC',
                                  'region': 'South/Latin America'},
     'Tuvalu': {'is_global_south': True, 'iso': 'TV', 'region': 'Asia & Pacific'},
     'Uganda': {'is_global_south': True, 'iso': 'UG', 'region': 'Africa'},
     'Ukraine': {'is_global_south': True, 'iso': 'UA', 'region': 'CIS'},
     'United Arab Emirates': {'is_global_south': True,
                              'iso': 'AE',
                              'region': 'Arab States'},
     'United Kingdom': {'is_global_south': False, 'iso': 'GB', 'region': 'Europe'},
     'United States': {'is_global_south': False,
                       'iso': 'US',
                       'region': 'North America'},
     'United States Minor Outlying Islands': {'is_global_south': True,
                                              'iso': 'UM',
                                              'region': 'Asia & Pacific'},
     'United States Virgin Islands': {'is_global_south': True,
                                      'iso': 'VI',
                                      'region': 'South/Latin America'},
     'Uruguay': {'is_global_south': True,
                 'iso': 'UY',
                 'region': 'South/Latin America'},
     'Uzbekistan': {'is_global_south': True, 'iso': 'UZ', 'region': 'CIS'},
     'Vanuatu': {'is_global_south': True, 'iso': 'VU', 'region': 'Asia & Pacific'},
     'Vatican City': {'is_global_south': False, 'iso': 'VA', 'region': 'Europe'},
     'Venezuela': {'is_global_south': True,
                   'iso': 'VE',
                   'region': 'South/Latin America'},
     'Vietnam': {'is_global_south': True, 'iso': 'VN', 'region': 'Asia & Pacific'},
     'Wallis and Futuna': {'is_global_south': True,
                           'iso': 'WF',
                           'region': 'Asia & Pacific'},
     'Western Sahara': {'is_global_south': True, 'iso': 'EH', 'region': 'Africa'},
     'Yemen': {'is_global_south': True, 'iso': 'YE', 'region': 'Arab States'},
     'Zambia': {'is_global_south': True, 'iso': 'ZM', 'region': 'Africa'},
     'Zimbabwe': {'is_global_south': True, 'iso': 'ZW', 'region': 'Africa'}
}

# global_south = []
# for country in country_info:
#     if country_info[country]["global_south"]:
#         global_south.append(country)
# print sorted(global_south)
# import pprint
# pprint.pprint(sorted(global_south))

pacific_rim_east = [
 'American Samoa',
 'Australia',
 'Brunei',
 'Cambodia',
 'China',
 'Cook Islands',
 'Timor-Leste',
 'Fiji',
 'French Polynesia',
 'Guam',
 'Hong Kong',
 'Indonesia',
 'Japan',
 'Kiribati',
 'Macau',
 'Malaysia',
 'Marshall Islands',
 'Micronesia',
 'Nauru',
 'New Caledonia',
 'New Zealand',
 'Niue',
 'Norfolk Island',
 'North Korea',
 'Northern Mariana Islands',
 'Palau',
 'Papua New Guinea',
 'Philippines',
 'Pitcairn Islands',
 'Russia',
 'Samoa',
 'Singapore',
 'Solomon Islands',
 'South Korea',
 'Taiwan',
 'Thailand',
 'Tokelau',
 'Tonga',
 'Tuvalu',
 'Vanuatu',
 'Vietnam',
 'Wallis and Futuna']


pacific_rim_west = [
 'Canada',
 'United States',
 'Mexico',
 'Guatemala',
 'El Salvador',
 'Honduras',
 'Nicaragua',
 'Costa Rica',
 'Panama',
 'Colombia',
 'Ecuador',
 'Peru',
 'Chile'
]
